### ISSUE TITLE
Design and change the Spatial Data Registry point structure

### ISSUE THREAD

**Issue by hollygrimm** [Kolektivo/geonft-registry-monorepo#2]

**Comment by rayedsikder** [comment]
The point structure will be a concatenation of latitude and longitude.
It will be concatenated and converted to hex value (bytes32) in web2. Then the bytes32 will be used as a key in a key-value pair mapping. 

It was observed in the previous experiments that accessing points array with larger number of elements fails very often due to lengthy traversals, hence a hash map based implementation will resolve the issue.
